<table>
    <tr>
        <th>S.No</th>
        <th>Name</th>
    </tr>
    <tbody>
        <tr>
            <td>1</td>
            <td>Chinni</td>
        </tr>
        <tr>
            <td>2</td>
            <td>Madhavi</td>
        </tr>
    </tbody>
</table>
